---

version: '3'
services:
  app:
    build: .
    environment:
      EPHEMERAL_REDIS_HOST: redis
      EPHEMERAL_SECRET_KEY: "${EPHEMERAL_SECRET_KEY}"
    ports:
      - "8080:8080"
    links:
      - redis
  redis:
    image: "redis:alpine"
